disable publish unidoc pom
```
[info] Nexus repository URL: https://oss.sonatype.org/service/local
[info] sonatypeProfileName = com.github.scalaprops
[info] Reading staging repository profiles...
[info] Reading staging profiles...
[info] Closing staging repository [comgithubscalaprops-1054] status:open, profile:com.github.scalaprops(5b63741c71c9d) description: Implicitly created (auto staging).
[info] Activity open started:2017-06-18T15:56:48.345Z, stopped:2017-06-18T15:56:52.945Z
[info] repositoryCreated: id:comgithubscalaprops-1054, user:xuwei-k, ip:115.65.179.254
[info] Activity close started:2017-06-18T16:03:13.827Z, stopped:2017-06-18T16:03:40.166Z
[info]   Evaluate: id:5e9e8e6f8d20a3, rule:sources-staging
[info]   Evaluate: signature-staging
[info]     Passed: signature-staging
[info]   Evaluate: javadoc-staging
[info]     Failed: javadoc-staging, failureMessage:Missing: no main jar artifact found in folder '/com/github/scalaprops/scalaprops-all_2.12/0.5.0'
[info]   Evaluate: sources-staging
[info]     Failed: sources-staging, failureMessage:Missing: no main jar artifact found in folder '/com/github/scalaprops/scalaprops-all_2.12/0.5.0'
[info]   Evaluate: checksum-staging
[info]     Passed: checksum-staging
[info]   Evaluate: pom-staging
[info]     Passed: pom-staging
[info]     Failed: id:5e9e8e6f8d20a3, failureCount:2
[info] repositoryCloseFailed: id:comgithubscalaprops-1054, cause:com.sonatype.nexus.staging.StagingRulesFailedException: One or more rules have failed
[info] Activity close started:2017-06-18T16:05:40.491Z, stopped:2017-06-18T16:06:05.278Z
[info]   Evaluate: id:5e9e8e6f8d20a3, rule:sources-staging
[info]   Evaluate: pom-staging
[info]     Passed: pom-staging
[info]   Evaluate: javadoc-staging
[info]     Failed: javadoc-staging, failureMessage:Missing: no main jar artifact found in folder '/com/github/scalaprops/scalaprops-all_2.12/0.5.0'
[info]   Evaluate: sources-staging
[info]     Failed: sources-staging, failureMessage:Missing: no main jar artifact found in folder '/com/github/scalaprops/scalaprops-all_2.12/0.5.0'
[info]   Evaluate: signature-staging
[info]     Passed: signature-staging
[info]   Evaluate: checksum-staging
[info]     Passed: checksum-staging
[info]     Failed: id:5e9e8e6f8d20a3, failureCount:2
[info] repositoryCloseFailed: id:comgithubscalaprops-1054, cause:com.sonatype.nexus.staging.StagingRulesFailedException: One or more rules have failed
[info] Activity close started:2017-06-18T16:07:31.007Z, stopped:2017-06-18T16:07:53.146Z
[info]   Evaluate: id:5e9e8e6f8d20a3, rule:sources-staging
[info]   Evaluate: pom-staging
[info]     Passed: pom-staging
[info]   Evaluate: checksum-staging
[info]     Passed: checksum-staging
[info]   Evaluate: sources-staging
[info]     Failed: sources-staging, failureMessage:Missing: no main jar artifact found in folder '/com/github/scalaprops/scalaprops-all_2.12/0.5.0'
[info]   Evaluate: javadoc-staging
[info]     Failed: javadoc-staging, failureMessage:Missing: no main jar artifact found in folder '/com/github/scalaprops/scalaprops-all_2.12/0.5.0'
[info]   Evaluate: signature-staging
[info]     Passed: signature-staging
[info]     Failed: id:5e9e8e6f8d20a3, failureCount:2
[info] repositoryCloseFailed: id:comgithubscalaprops-1054, cause:com.sonatype.nexus.staging.StagingRulesFailedException: One or more rules have failed
[info] Activity close started:2017-06-18T16:09:19.083Z, stopped:
[info]   Evaluate: id:5e9e8e6f8d20a3, rule:sources-staging
[info]   Evaluate: signature-staging
[info]     Passed: signature-staging
[info]   Evaluate: pom-staging
[info]     Passed: pom-staging
[info]   Evaluate: checksum-staging
[info]     Passed: checksum-staging
[info]   Evaluate: sources-staging
[info]     Failed: sources-staging, failureMessage:Missing: no main jar artifact found in folder '/com/github/scalaprops/scalaprops-all_2.12/0.5.0'
[info]   Evaluate: javadoc-staging
[info]     Failed: javadoc-staging, failureMessage:Missing: no main jar artifact found in folder '/com/github/scalaprops/scalaprops-all_2.12/0.5.0'
[info]     Failed: id:5e9e8e6f8d20a3, failureCount:2
[info] repositoryCloseFailed: id:comgithubscalaprops-1054, cause:com.sonatype.nexus.staging.StagingRulesFailedException: One or more rules have failed
[error] Failed to close the repository
[error] Activity close started:2017-06-18T16:09:19.083Z, stopped:2017-06-18T16:09:44.365Z
[error]     Failed: sources-staging, failureMessage:Missing: no main jar artifact found in folder '/com/github/scalaprops/scalaprops-all_2.12/0.5.0'
[error]     Failed: javadoc-staging, failureMessage:Missing: no main jar artifact found in folder '/com/github/scalaprops/scalaprops-all_2.12/0.5.0'
java.lang.Exception: Failed to close the repository
	at xerial.sbt.Sonatype$NexusRESTService.closeStage(Sonatype.scala:717)
	at xerial.sbt.Sonatype$NexusRESTService.closeAndPromote(Sonatype.scala:816)
	at xerial.sbt.Sonatype$SonatypeCommand$$anonfun$19.apply(Sonatype.scala:206)
	at xerial.sbt.Sonatype$SonatypeCommand$$anonfun$19.apply(Sonatype.scala:198)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	at sbt.Command$.process(Command.scala:93)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	at sbt.State$$anon$1.doX$1(State.scala:183)
	at sbt.State$$anon$1.process(State.scala:190)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.MainLoop$.next(MainLoop.scala:96)
	at sbt.MainLoop$.run(MainLoop.scala:89)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
	at sbt.MainLoop$.runLogged(MainLoop.scala:22)
	at sbt.StandardMain$.runManaged(Main.scala:109)
	at sbt.xMain.run(Main.scala:38)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.Exception: Failed to close the repository
[error] Use 'last' for the full log.
```